replicaCount: 1

image:
  repository: codingwulf/invento-hub-inventory-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
